"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import { ThemeProvider } from '@mui/material/styles';
import Theme from '@/styled/theme/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ThemeProvider theme={Theme}>

    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </ThemeProvider>
  )
}
